### ISSUE TITLE
PCB design files

### ISSUE THREAD

**Issue by samuk** [Bettys-sidepiece/Project-Isla#2]
Do you still have the Eagle/Kicad for this project? Could you upload them?

**Comment by Bettys-sidepiece** [comment]
Hi @samuk, unfortunately not I am working on newer designs using kicad that will be uploaded as soon as early may.

**Comment by samuk** [comment]
Nice, will you be releasing the source for the new version as well?

This is the one I'm working on https://rosmo-robot.github.io/ progress a little slow at the moment

**Comment by Bettys-sidepiece** [comment]
@samuk Yes I will be releasing the source.

**Comment by samuk** [comment]
Will you be sticking with the TB6612FNG for this iteration?

I'm thinking of doing a Pico-RP2040, TB6612FNG with dual N20/encoder https://www.aliexpress.com/item/1005002307903318.html

I might just wait for yours if it's very similar..

**Comment by Bettys-sidepiece** [comment]
Yes I plan on using the same motor driver and motors (with a higher rpm) this new design will also have fixes for the previous design, and will also feature a 6 dof imu, and motor current sense.

**Comment by samuk** [comment]
Nice, looking forward to it!

FWIW I opted to include a UEXT socket on the larger 4x4 bot, so users could [choose their own](https://github.com/rosmo-robot/smartcar_shield#optional-sensors) OSHW modules from Olimex

Also including a couple of  5pin I2C in [Breakout Garden](https://hackaday.com/2022/05/04/the-connector-zoo-i2c-ecosystems/) format
